/** Seed data for Featured Experiences — used only by seed script, not served to clients directly. */

function blogSeed({
  slug,
  title,
  heroImage,
  region,
  overview,
  whyVisit,
  bestTime,
  things,
  nearby,
  howToReach,
  tips,
  gallery,
  lat,
  lng,
  relatedSlugs = [],
  categoryTags = [],
}) {
  return {
    slug,
    title,
    subtitle: region,
    heroImage,
    overview,
    whyVisit,
    bestTimeToVisit: bestTime,
    thingsToDo: things.map((label) => ({ label, detail: '' })),
    nearbyAttractions: nearby.map((n) => ({
      slug: n.slug,
      title: n.title,
      image: n.image || heroImage,
    })),
    howToReach,
    travelTips: tips,
    gallery: gallery?.length ? gallery : [heroImage],
    map: lat != null ? { lat, lng, query: title } : undefined,
    relatedSlugs,
    categoryTags,
    published: true,
    seo: {
      title: `${title} — Maharashtra Travel Guide`,
      description: overview?.slice(0, 155),
      keywords: `${title}, Maharashtra tourism, travel guide`,
      ogImage: heroImage,
    },
  };
}

const IMG = {
  waterfall: '/curated/monsoon-trails/devkund-waterfall.jpg',
  thoseghar: '/curated/monsoon-trails/thoseghar-waterfalls.jpg',
  tamhini: '/curated/monsoon-trails/tamhini-ghat.jpg',
  visapur: '/curated/monsoon-trails/visapur-fort.jpg',
  fort: '/categories/explorer/adventure.jpg',
  hills: '/categories/explorer/home-3.jpg',
  trek: '/categories/explorer/adventure.jpg',
};

export function getDefaultExperienceBlogs() {
  const commonTips = [
    'Carry rain gear and non-slip footwear in monsoon.',
    'Start early to avoid afternoon cloud cover on ghats.',
    'Check local weather and road closures before you leave.',
  ];

  const blogs = [
    blogSeed({
      slug: 'devkund-waterfall',
      title: 'Devkund Waterfall',
      heroImage: IMG.waterfall,
      region: 'Raigad · Monsoon',
      overview:
        'A turquoise plunge pool fed by a multi-tier cascade in the Tamhini backcountry — one of Maharashtra’s most photogenic monsoon day hikes.',
      whyVisit:
        'Devkund combines forest trail, river crossing, and a dramatic waterfall finale in a single half-day outing from Mumbai and Pune.',
      bestTime: 'July–September during active monsoon; avoid heavy flood warnings.',
      things: ['Forest trek', 'Waterfall photography', 'Picnic by the pool', 'Monsoon mist views'],
      nearby: [
        { slug: 'tamhini-ghat', title: 'Tamhini Ghat' },
        { slug: 'thoseghar-waterfalls', title: 'Thoseghar Waterfalls' },
      ],
      howToReach:
        'Drive to Bhira village near Tamhini; local guides and forest rules apply — park at designated lots and trek the marked route.',
      tips: [...commonTips, 'Respect forest department guidelines and do not swim in high flow.'],
      lat: 18.45,
      lng: 73.42,
      relatedSlugs: ['tamhini-ghat', 'thoseghar-waterfalls', 'bhandardara'],
      categoryTags: ['monsoon-waterfalls', 'monsoon-treks'],
    }),
    blogSeed({
      slug: 'thoseghar-waterfalls',
      title: 'Thoseghar Waterfalls',
      heroImage: IMG.thoseghar,
      region: 'Satara · Monsoon',
      overview:
        'A series of seasonal falls in the Sahyadri escarpment, best known for wide cascades and misty viewpoints above the Konkan fringe.',
      whyVisit: 'Easy access from Satara makes Thoseghar a classic monsoon road-trip stop with multiple viewing decks.',
      bestTime: 'June–September',
      things: ['Viewpoint walks', 'Monsoon photography', 'Short nature trails'],
      nearby: [
        { slug: 'vajrai-waterfall', title: 'Vajrai Waterfall' },
        { slug: 'mahabaleshwar', title: 'Mahabaleshwar' },
      ],
      howToReach: 'Satara–Thoseghar road; ~20 km from Satara city with signed parking near the falls.',
      tips: commonTips,
      lat: 17.62,
      lng: 73.86,
      relatedSlugs: ['vajrai-waterfall', 'mahabaleshwar', 'lingmala-waterfall'],
      categoryTags: ['monsoon-waterfalls'],
    }),
    blogSeed({
      slug: 'vajrai-waterfall',
      title: 'Vajrai Waterfall',
      heroImage: IMG.waterfall,
      region: 'Satara plateau',
      overview: 'Among the tallest seasonal falls near Bhambavli village, plunging over the escarpment into the Konkan.',
      whyVisit: 'Sheer drop and cloud-base views draw photographers during peak monsoon.',
      bestTime: 'July–August',
      things: ['Viewing points', 'Plateau drives', 'Village walks'],
      nearby: [{ slug: 'thoseghar-waterfalls', title: 'Thoseghar Waterfalls' }],
      howToReach: 'Bhambavli village access via Satara; hire local guidance in wet season.',
      tips: commonTips,
      relatedSlugs: ['thoseghar-waterfalls', 'mahabaleshwar'],
      categoryTags: ['monsoon-waterfalls'],
    }),
    blogSeed({
      slug: 'randha-falls',
      title: 'Randha Falls',
      heroImage: IMG.hills,
      region: 'Bhandardara · Ahmednagar',
      overview: 'The Pravara River drops over a basalt rim near Bhandardara — a classic monsoon panorama above Arthur Lake.',
      whyVisit: 'Pairs naturally with firefly season, lake stays, and Kalsubai treks.',
      bestTime: 'Monsoon and post-monsoon (June–October)',
      things: ['River gorge views', 'Bhandardara lake circuit', 'Temple visits'],
      nearby: [{ slug: 'bhandardara', title: 'Bhandardara' }],
      howToReach: 'Igatpuri–Bhandardara road; falls signposted from village.',
      tips: commonTips,
      relatedSlugs: ['bhandardara', 'harishchandragad-fort'],
      categoryTags: ['monsoon-waterfalls', 'cloud-walks'],
    }),
    blogSeed({
      slug: 'lingmala-waterfall',
      title: 'Lingmala Waterfall',
      heroImage: IMG.hills,
      region: 'Mahabaleshwar',
      overview: 'A forest-framed cascade on the Mahabaleshwar plateau, popular for short walks from the main hill-station roads.',
      whyVisit: 'Easy monsoon add-on to a Mahabaleshwar weekend without a long trek.',
      bestTime: 'June–September',
      things: ['Forest walk', 'Waterfall viewpoints', 'Strawberry country stops'],
      nearby: [{ slug: 'mahabaleshwar', title: 'Mahabaleshwar' }],
      howToReach: 'Signed turnoff on Mahabaleshwar–Panchgani routes; parking at trailhead.',
      tips: commonTips,
      relatedSlugs: ['mahabaleshwar', 'thoseghar-waterfalls'],
      categoryTags: ['monsoon-waterfalls'],
    }),
    blogSeed({
      slug: 'tamhini-ghat',
      title: 'Tamhini Ghat',
      heroImage: IMG.tamhini,
      region: 'Pune–Konkan corridor',
      overview:
        'A winding rainforest road between the Deccan plateau and Konkan coast — waterfalls, mist, and endemic birds in monsoon.',
      whyVisit: 'One of Maharashtra’s most cinematic monsoon drives with short hike-offs at every turn.',
      bestTime: 'June–September for mist; post-monsoon for clearer views.',
      things: ['Scenic drives', 'Waterfall stops', 'Birding', 'Photography pullouts'],
      nearby: [
        { slug: 'devkund-waterfall', title: 'Devkund Waterfall' },
        { slug: 'malshej-ghat', title: 'Malshej Ghat' },
      ],
      howToReach: 'Pune–Tamhini–Kolad road; allow extra time for fog and traffic on weekends.',
      tips: [...commonTips, 'Drive in daylight; use low beam in fog.'],
      lat: 18.45,
      lng: 73.42,
      relatedSlugs: ['malshej-ghat', 'amboli-ghat', 'devkund-waterfall'],
      categoryTags: ['monsoon-drives', 'cloud-walks'],
    }),
    blogSeed({
      slug: 'malshej-ghat',
      title: 'Malshej Ghat',
      heroImage: IMG.tamhini,
      region: 'Thane–Ahmednagar',
      overview: 'Flamingo-grey skies, tunnel mist, and seasonal falls along the Kalyan–Murbad plateau road.',
      whyVisit: 'Legendary monsoon drive from Mumbai with minimal planning.',
      bestTime: 'July–August peak mist',
      things: ['Ghat drive', 'Waterfall viewpoints', 'Harishchandragad approaches'],
      nearby: [{ slug: 'harishchandragad-fort', title: 'Harishchandragad' }],
      howToReach: 'NH via Kalyan–Murbad–Malshej; check monsoon road advisories.',
      tips: commonTips,
      relatedSlugs: ['tamhini-ghat', 'amboli-ghat', 'bhandardara'],
      categoryTags: ['monsoon-drives', 'cloud-walks'],
    }),
    blogSeed({
      slug: 'amboli-ghat',
      title: 'Amboli Ghat',
      heroImage: IMG.hills,
      region: 'Sindhudurg · Western Ghats',
      overview: 'High rainfall biodiversity hotspot where the Sahyadris meet the Konkan — mist, frogs, and forest streams.',
      whyVisit: 'Cooler temperatures and lush canopy even when the Deccan is dry.',
      bestTime: 'Monsoon through winter',
      things: ['Nature walks', 'Sunset points', 'Waterfall trails'],
      nearby: [{ slug: 'amboli', title: 'Amboli' }],
      howToReach: 'Sawantwadi–Amboli ghat road; stay in Amboli town.',
      tips: commonTips,
      relatedSlugs: ['amboli', 'varandha-ghat'],
      categoryTags: ['monsoon-drives'],
    }),
    blogSeed({
      slug: 'varandha-ghat',
      title: 'Varandha Ghat',
      heroImage: IMG.hills,
      region: 'Pune–Konkan',
      overview: 'Historic trade route with hairpin bends, valley views, and monsoon clouds pouring into the Konkan.',
      whyVisit: 'Quieter alternative to Tamhini with big-sky vistas.',
      bestTime: 'Monsoon and early winter',
      things: ['Scenic drive', 'Valley photography', 'Fort detours'],
      nearby: [{ slug: 'rajgad-fort', title: 'Rajgad Fort' }],
      howToReach: 'Bhor–Mahad road across Varandha pass.',
      tips: commonTips,
      relatedSlugs: ['ambenali-ghat', 'tamhini-ghat'],
      categoryTags: ['monsoon-drives'],
    }),
    blogSeed({
      slug: 'ambenali-ghat',
      title: 'Ambenali Ghat',
      heroImage: IMG.hills,
      region: 'Raigad · Konkan link',
      overview: 'Coastal-ward descent with sweeping views toward the Konkan — dramatic in monsoon cloud inversions.',
      whyVisit: 'Connects plateau forts and Konkan beaches in one long scenic day.',
      bestTime: 'June–October',
      things: ['Ghat photography', 'Road trip stops'],
      nearby: [{ slug: 'raigad-fort', title: 'Raigad Fort' }],
      howToReach: 'Mahad–Poladpur plateau connectors; verify ghat status in heavy rain.',
      tips: commonTips,
      relatedSlugs: ['varandha-ghat', 'tamhini-ghat'],
      categoryTags: ['monsoon-drives'],
    }),
    blogSeed({
      slug: 'rajgad-fort',
      title: 'Rajgad Fort',
      heroImage: IMG.fort,
      region: 'Pune district · Sahyadri',
      overview: 'Capital fort of Shivaji Maharaj — sprawling plateaus, bastions, and monsoon cloud seas.',
      whyVisit: 'History and high-altitude mist in one trek.',
      bestTime: 'Monsoon for drama; winter for clearer views.',
      things: ['Fort exploration', 'Padmavati machi', 'Sanjeevani machi views'],
      nearby: [{ slug: 'tamhini-ghat', title: 'Tamhini Ghat' }],
      howToReach: 'Base villages Pali or Gunjavane; full-day trek.',
      tips: [...commonTips, 'Carry water and trekking poles on wet rock.'],
      relatedSlugs: ['raigad-fort', 'lohagad-fort', 'harishchandragad-fort'],
      categoryTags: ['mist-forts', 'monsoon-treks'],
    }),
    blogSeed({
      slug: 'raigad-fort',
      title: 'Raigad Fort',
      heroImage: IMG.fort,
      region: 'Raigad district',
      overview: 'Hill capital with ropeway access and vast monsoon cloud decks over the Konkan.',
      whyVisit: 'Accessible fort with iconic Maratha history.',
      bestTime: 'June–February',
      things: ['Ropeway', 'Palace ruins', 'Valley views'],
      nearby: [{ slug: 'rajmachi-fort', title: 'Rajmachi Fort' }],
      howToReach: 'Pachad ropeway or trek from Pachad/Mahad side.',
      tips: commonTips,
      relatedSlugs: ['rajgad-fort', 'pratapgad-fort'],
      categoryTags: ['mist-forts'],
    }),
    blogSeed({
      slug: 'pratapgad-fort',
      title: 'Pratapgad Fort',
      heroImage: IMG.fort,
      region: 'Satara · Western Ghats',
      overview: 'Clifftop fort above the Koyna valley — sheer drops and monsoon fog rolling up from the west.',
      whyVisit: 'Short drives from Mahabaleshwar combine plateau food with fort drama.',
      bestTime: 'Monsoon through winter',
      things: ['Fort ramparts', 'Shivaji memorial', 'Valley photography'],
      nearby: [{ slug: 'mahabaleshwar', title: 'Mahabaleshwar' }],
      howToReach: 'Mahabaleshwar–Poladpur road; stair access to upper fort.',
      tips: commonTips,
      relatedSlugs: ['rajgad-fort', 'mahabaleshwar'],
      categoryTags: ['mist-forts'],
    }),
    blogSeed({
      slug: 'lohagad-fort',
      title: 'Lohagad Fort',
      heroImage: IMG.visapur,
      region: 'Lonavala · Sahyadri',
      overview: 'Popular monsoon trek with the famous “Vinchu Kata” scorpion-tail ridge often floating in clouds.',
      whyVisit: 'Easy day trek from Mumbai/Pune with big payoff views.',
      bestTime: 'June–September',
      things: ['Fort walk', 'Monsoon photography', 'Bhaja caves nearby'],
      nearby: [{ slug: 'korigad-fort', title: 'Korigad Fort' }],
      howToReach: 'Malavli station trek or drive to Lohagad village parking.',
      tips: commonTips,
      relatedSlugs: ['korigad-fort', 'rajmachi-fort', 'karnala-fort'],
      categoryTags: ['mist-forts', 'monsoon-treks'],
    }),
    blogSeed({
      slug: 'harishchandragad-fort',
      title: 'Harishchandragad Fort',
      heroImage: IMG.fort,
      region: 'Ahmednagar · Kalsubai range',
      overview: 'Konkan Kada cliff and ancient caves — legendary camping spot when clouds pour over the edge.',
      whyVisit: 'Among the most dramatic Sahyadri vistas in monsoon.',
      bestTime: 'Post-monsoon and winter for camping; monsoon for clouds (expert trekkers only).',
      things: ['Konkan Kada', 'Trekking', 'Night sky (winter)'],
      nearby: [{ slug: 'bhandardara', title: 'Bhandardara' }],
      howToReach: 'Multiple routes (Pachnai, Khireshwar); choose per fitness and weather.',
      tips: [...commonTips, 'Avoid exposed edges in high wind.'],
      relatedSlugs: ['bhandardara', 'malshej-ghat'],
      categoryTags: ['mist-forts', 'cloud-walks'],
    }),
    blogSeed({
      slug: 'mahabaleshwar',
      title: 'Mahabaleshwar',
      heroImage: IMG.hills,
      region: 'Satara plateau',
      overview: 'Strawberry hills, colonial walks, and monsoon clouds that swallow the valleys whole.',
      whyVisit: 'Classic hill station with viewpoints minutes apart.',
      bestTime: 'Monsoon mist; March–June for strawberries.',
      things: ['Echo Point', 'Mapro garden', 'Venna Lake', 'Plateau drives'],
      nearby: [{ slug: 'lingmala-waterfall', title: 'Lingmala Waterfall' }],
      howToReach: 'Pune–Wai–Mahabaleshwar highway; MTDC buses from major cities.',
      tips: commonTips,
      relatedSlugs: ['malshej-ghat', 'bhandardara', 'amboli'],
      categoryTags: ['cloud-walks'],
    }),
    blogSeed({
      slug: 'bhandardara',
      title: 'Bhandardara',
      heroImage: IMG.hills,
      region: 'Arthur Lake · Ahmednagar',
      overview: 'Lake district of the Sahyadris — dams, falls, and firefly meadows under monsoon skies.',
      whyVisit: 'Relaxed base for Randha Falls and Kalsubai approaches.',
      bestTime: 'Monsoon and pre-monsoon fireflies.',
      things: ['Arthur Lake', 'Randha Falls', 'Wilson Dam', 'Village stays'],
      nearby: [{ slug: 'randha-falls', title: 'Randha Falls' }],
      howToReach: 'Igatpuri–Ghoti–Bhandardara; winding but scenic.',
      tips: commonTips,
      relatedSlugs: ['mahabaleshwar', 'harishchandragad-fort', 'malshej-ghat'],
      categoryTags: ['cloud-walks'],
    }),
    blogSeed({
      slug: 'amboli',
      title: 'Amboli',
      heroImage: IMG.hills,
      region: 'Sindhudurg hills',
      overview: 'Wettest corner of Maharashtra — misty forests, frogs, and quiet homestays.',
      whyVisit: 'Cool escape with biodiversity walks.',
      bestTime: 'Monsoon through early winter',
      things: ['Sunset point', 'Nangartas fall', 'Forest trails'],
      nearby: [{ slug: 'amboli-ghat', title: 'Amboli Ghat' }],
      howToReach: 'Sawantwadi–Amboli; combine with Goa or Konkan coast trips.',
      tips: commonTips,
      relatedSlugs: ['amboli-ghat', 'mahabaleshwar'],
      categoryTags: ['cloud-walks'],
    }),
    blogSeed({
      slug: 'rajmachi-fort',
      title: 'Rajmachi Fort',
      heroImage: IMG.trek,
      region: 'Lonavala–Khandala',
      overview: 'Twin forts guarding the Bor ghat — monsoon meadows and cloud tunnels on the plateau.',
      whyVisit: 'Overnight trek classic with village stays.',
      bestTime: 'Monsoon and winter',
      things: ['Shrivardhan & Manaranjan forts', 'Village camping', 'Valley views'],
      nearby: [{ slug: 'korigad-fort', title: 'Korigad Fort' }],
      howToReach: 'Trek from Udhewadi or Lonavala side; 4WD in dry season only.',
      tips: commonTips,
      relatedSlugs: ['lohagad-fort', 'korigad-fort', 'karnala-fort'],
      categoryTags: ['monsoon-treks'],
    }),
    blogSeed({
      slug: 'korigad-fort',
      title: 'Korigad Fort',
      heroImage: IMG.fort,
      region: 'Lonavala hills',
      overview: 'Compact fort with wide plateau walls — quick monsoon hike with lake views.',
      whyVisit: 'Half-day trek suitable for beginners.',
      bestTime: 'June–February',
      things: ['Fort circuit', 'Temple', 'Aamby Valley views'],
      nearby: [{ slug: 'lohagad-fort', title: 'Lohagad Fort' }],
      howToReach: 'Peth Shahapur village base; ~1 hour climb.',
      tips: commonTips,
      relatedSlugs: ['lohagad-fort', 'rajmachi-fort'],
      categoryTags: ['monsoon-treks'],
    }),
    blogSeed({
      slug: 'karnala-fort',
      title: 'Karnala Fort',
      heroImage: IMG.trek,
      region: 'Raigad · Bird sanctuary',
      overview: 'Spiral trail through bird sanctuary forest to a thumb-shaped pinnacle.',
      whyVisit: 'Mumbai day-trip trek with birding bonus.',
      bestTime: 'Winter birding; monsoon for greenery.',
      things: ['Sanctuary walk', 'Fort summit', 'Birding'],
      nearby: [{ slug: 'karnala-fort', title: 'Karnala Bird Sanctuary' }],
      howToReach: 'Karnala sanctuary entrance off NH48; permit at gate.',
      tips: commonTips,
      relatedSlugs: ['peb-fort', 'korigad-fort'],
      categoryTags: ['monsoon-treks'],
    }),
    blogSeed({
      slug: 'peb-fort',
      title: 'Peb Fort (Vikatgad)',
      heroImage: IMG.trek,
      region: 'Matheran range',
      overview: 'Rocky steps and caves on a lesser-known Matheran satellite fort.',
      whyVisit: 'Quiet alternative when Karjat trails are crowded.',
      bestTime: 'Monsoon and winter',
      things: ['Cave exploration', 'Summit views', 'Rock scrambling'],
      nearby: [{ slug: 'karnala-fort', title: 'Karnala Fort' }],
      howToReach: 'Shedung village trail near Neral/Karjat.',
      tips: commonTips,
      relatedSlugs: ['rajmachi-fort', 'karnala-fort'],
      categoryTags: ['monsoon-treks'],
    }),
  ];

  return blogs;
}

export function getDefaultFeaturedCategories() {
  return [
    {
      slug: 'monsoon-waterfalls',
      title: 'Must-Visit Waterfalls in Maharashtra This Monsoon',
      description:
        'Plunge pools, misty cascades, and forest trails that come alive when the rains return.',
      coverImage: IMG.waterfall,
      exploreHref: '/explore',
      sortOrder: 1,
      published: true,
      activities: [
        { title: 'Devkund Waterfall', blogSlug: 'devkund-waterfall', sortOrder: 0 },
        { title: 'Thoseghar Waterfalls', blogSlug: 'thoseghar-waterfalls', sortOrder: 1 },
        { title: 'Vajrai Waterfall', blogSlug: 'vajrai-waterfall', sortOrder: 2 },
        { title: 'Randha Falls', blogSlug: 'randha-falls', sortOrder: 3 },
        { title: 'Lingmala Waterfall', blogSlug: 'lingmala-waterfall', sortOrder: 4 },
      ],
    },
    {
      slug: 'monsoon-drives',
      title: 'Most Scenic Monsoon Drives in Maharashtra',
      description: 'Hairpin bends, tunnel mist, and waterfall pullouts along the Sahyadri rim.',
      coverImage: IMG.tamhini,
      exploreHref: '/explore',
      sortOrder: 2,
      published: true,
      activities: [
        { title: 'Tamhini Ghat', blogSlug: 'tamhini-ghat', sortOrder: 0 },
        { title: 'Malshej Ghat', blogSlug: 'malshej-ghat', sortOrder: 1 },
        { title: 'Amboli Ghat', blogSlug: 'amboli-ghat', sortOrder: 2 },
        { title: 'Varandha Ghat', blogSlug: 'varandha-ghat', sortOrder: 3 },
        { title: 'Ambenali Ghat', blogSlug: 'ambenali-ghat', sortOrder: 4 },
      ],
    },
    {
      slug: 'mist-forts',
      title: 'Historic Forts Wrapped in Mist',
      description: 'Maratha ramparts and ridge walks when the monsoon pours through the battlements.',
      coverImage: IMG.fort,
      exploreHref: '/explore',
      sortOrder: 3,
      published: true,
      activities: [
        { title: 'Rajgad Fort', blogSlug: 'rajgad-fort', sortOrder: 0 },
        { title: 'Raigad Fort', blogSlug: 'raigad-fort', sortOrder: 1 },
        { title: 'Pratapgad Fort', blogSlug: 'pratapgad-fort', sortOrder: 2 },
        { title: 'Lohagad Fort', blogSlug: 'lohagad-fort', sortOrder: 3 },
        { title: 'Harishchandragad Fort', blogSlug: 'harishchandragad-fort', sortOrder: 4 },
      ],
    },
    {
      slug: 'cloud-walks',
      title: "Places Where You'll Walk Through the Clouds",
      description: 'Hill stations and ghats where the horizon disappears into white.',
      coverImage: IMG.hills,
      exploreHref: '/explore',
      sortOrder: 4,
      published: true,
      activities: [
        { title: 'Malshej Ghat', blogSlug: 'malshej-ghat', sortOrder: 0 },
        { title: 'Tamhini Ghat', blogSlug: 'tamhini-ghat', sortOrder: 1 },
        { title: 'Mahabaleshwar', blogSlug: 'mahabaleshwar', sortOrder: 2 },
        { title: 'Bhandardara', blogSlug: 'bhandardara', sortOrder: 3 },
        { title: 'Amboli', blogSlug: 'amboli', sortOrder: 4 },
      ],
    },
    {
      slug: 'monsoon-treks',
      title: 'One-Day Monsoon Treks Near Mumbai',
      description: 'Summit forts and forest ridges you can complete before sundown.',
      coverImage: IMG.trek,
      exploreHref: '/explore',
      sortOrder: 5,
      published: true,
      activities: [
        { title: 'Lohagad Fort', blogSlug: 'lohagad-fort', sortOrder: 0 },
        { title: 'Rajmachi Fort', blogSlug: 'rajmachi-fort', sortOrder: 1 },
        { title: 'Korigad Fort', blogSlug: 'korigad-fort', sortOrder: 2 },
        { title: 'Karnala Fort', blogSlug: 'karnala-fort', sortOrder: 3 },
        { title: 'Peb Fort (Vikatgad)', blogSlug: 'peb-fort', sortOrder: 4 },
      ],
    },
  ];
}
